"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.default = exports.DRAG_INTO_TOPMOST_DIRECTORIES_ONLY = exports.REMOVE_EMPTY_PARENT_DIRECTORIES = void 0;
var REMOVE_EMPTY_PARENT_DIRECTORIES = "REMOVE_EMPTY_PARENT_DIRECTORIES";
exports.REMOVE_EMPTY_PARENT_DIRECTORIES = REMOVE_EMPTY_PARENT_DIRECTORIES;
var DRAG_INTO_TOPMOST_DIRECTORIES_ONLY = "DRAG_INTO_TOPMOST_DIRECTORIES_ONLY";
exports.DRAG_INTO_TOPMOST_DIRECTORIES_ONLY = DRAG_INTO_TOPMOST_DIRECTORIES_ONLY;
var _default = {
    REMOVE_EMPTY_PARENT_DIRECTORIES: REMOVE_EMPTY_PARENT_DIRECTORIES,
    DRAG_INTO_TOPMOST_DIRECTORIES_ONLY: DRAG_INTO_TOPMOST_DIRECTORIES_ONLY
};
exports.default = _default;
