"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.FILE_NAME_MARKER_TYPE = exports.DIRECTORY_NAME_DRAG_TYPE = exports.DIRECTORY_NAME_MARKER_TYPE = exports.FILE_NAME_DRAG_TYPE = void 0;
var FILE_NAME_DRAG_TYPE = "file";
exports.FILE_NAME_DRAG_TYPE = FILE_NAME_DRAG_TYPE;
var FILE_NAME_MARKER_TYPE = "file-marker";
exports.FILE_NAME_MARKER_TYPE = FILE_NAME_MARKER_TYPE;
var DIRECTORY_NAME_DRAG_TYPE = "directory";
exports.DIRECTORY_NAME_DRAG_TYPE = DIRECTORY_NAME_DRAG_TYPE;
var DIRECTORY_NAME_MARKER_TYPE = "directory-marker";
exports.DIRECTORY_NAME_MARKER_TYPE = DIRECTORY_NAME_MARKER_TYPE;
