"use strict";

export const OPEN_CUSTOM_EVENT_TYPE = "open";
export const MOVE_CUSTOM_EVENT_TYPE = "move";
export const CHANGE_CUSTOM_EVENT_TYPE = "change";
export const CANCEL_CUSTOM_EVENT_TYPE = "cancel";
export const SELECT_CUSTOM_EVENT_TYPE = "select";
export const RENAME_CUSTOM_EVENT_TYPE = "rename";
export const REMOVE_CUSTOM_EVENT_TYPE = "remove";
export const CREATE_CUSTOM_EVENT_TYPE = "create";

export default {
  OPEN_CUSTOM_EVENT_TYPE,
  MOVE_CUSTOM_EVENT_TYPE,
  CHANGE_CUSTOM_EVENT_TYPE,
  CANCEL_CUSTOM_EVENT_TYPE,
  SELECT_CUSTOM_EVENT_TYPE,
  RENAME_CUSTOM_EVENT_TYPE,
  REMOVE_CUSTOM_EVENT_TYPE,
  CREATE_CUSTOM_EVENT_TYPE
};