"use strict";

export const REMOVE_EMPTY_PARENT_DIRECTORIES = "REMOVE_EMPTY_PARENT_DIRECTORIES";
export const DRAG_INTO_TOPMOST_DIRECTORIES_ONLY = "DRAG_INTO_TOPMOST_DIRECTORIES_ONLY";

export default {
  REMOVE_EMPTY_PARENT_DIRECTORIES,
  DRAG_INTO_TOPMOST_DIRECTORIES_ONLY
};
