"use strict";

export const REMOVE_EMPTY_PARENT_DIRECTORIES_OPTION = "REMOVE_EMPTY_PARENT_DIRECTORIES_OPTION";
export const DRAG_INTO_TOPMOST_DIRECTORIES_ONLY_OPTION = "DRAG_INTO_TOPMOST_DIRECTORIES_ONLY_OPTION";

export default {
  REMOVE_EMPTY_PARENT_DIRECTORIES_OPTION,
  DRAG_INTO_TOPMOST_DIRECTORIES_ONLY_OPTION
};
