"use strict";

export const DRAG_INTO_RUBBISH_BIN_ONLY = "DRAG_INTO_RUBBISH_BIN_ONLY";
export const DRAG_INTO_TOPMOST_DIRECTORIES_ONLY = "DRAG_INTO_TOPMOST_DIRECTORIES_ONLY";

export default {
  DRAG_INTO_RUBBISH_BIN_ONLY,
  DRAG_INTO_TOPMOST_DIRECTORIES_ONLY
};
