"use strict";

export const FILE_NAME_DRAG_TYPE = "FILE_NAME_DRAG_TYPE";
export const FILE_NAME_MARKER_TYPE = "FILE_NAME_MARKER_TYPE";
export const DIRECTORY_NAME_DRAG_TYPE = "DIRECTORY_NAME_DRAG_TYPE";
export const DIRECTORY_NAME_MARKER_TYPE = "DIRECTORY_NAME_MARKER_TYPE";
